# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  akstestapp:
    image: akstestapp
    build:
      context: .
      dockerfile: AKS-Test-app/AKS-Test-app/Dockerfile
    ports:
      - 80:80
